
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'A5D6830B83A9854F85FDA44984CC7530'
    
_lr_action_items = {'leftbrace':([10,],[16,]),'puts':([7,13,17,18,19,32,34,35,36,37,],[12,12,-11,-12,12,-9,-16,-13,-14,-15,]),'arrayeach':([4,29,],[9,-3,]),'number':([6,12,16,20,28,30,31,],[11,18,22,26,22,35,37,]),'EQUAL':([3,5,14,],[6,10,20,]),'tag':([9,],[15,]),'COMMA':([22,],[28,]),'rightbrace':([16,22,23,24,33,],[-5,-7,29,-4,-6,]),'operator':([15,25,26,27,],[21,30,31,32,]),'STRING':([12,],[17,]),'identifier':([0,1,7,11,13,17,18,19,20,21,30,31,32,34,35,36,37,],[3,5,14,-2,14,-11,-12,14,25,27,34,36,-9,-16,-13,-14,-15,]),'$end':([2,8,13,17,18,19,34,35,36,37,],[0,-1,-8,-11,-12,-10,-16,-13,-14,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'a':([0,],[1,]),'b':([1,],[4,]),'fline':([4,],[7,]),'iterator':([4,],[8,]),'optionalargs':([16,],[23,]),'args':([16,28,],[24,33,]),'lines':([7,13,19,],[13,19,19,]),'expres':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expres","S'",1,None,None,None),
  ('expres -> a b iterator','expres',3,'p_starting','mygrammar.py',27),
  ('a -> identifier EQUAL number','a',3,'p_assignment','mygrammar.py',31),
  ('b -> identifier EQUAL leftbrace optionalargs rightbrace','b',5,'p_arrayassignment','mygrammar.py',35),
  ('optionalargs -> args','optionalargs',1,'p_optionalargs','mygrammar.py',38),
  ('optionalargs -> <empty>','optionalargs',0,'p_optionalargsempty','mygrammar.py',41),
  ('args -> number COMMA args','args',3,'p_args','mygrammar.py',44),
  ('args -> number','args',1,'p_argslast','mygrammar.py',47),
  ('iterator -> fline lines','iterator',2,'p_iterator','mygrammar.py',51),
  ('fline -> arrayeach tag operator identifier operator','fline',5,'p_fline','mygrammar.py',55),
  ('lines -> lines lines','lines',2,'p_lines','mygrammar.py',59),
  ('lines -> puts STRING','lines',2,'p_lines1','mygrammar.py',63),
  ('lines -> puts number','lines',2,'p_lines2','mygrammar.py',67),
  ('lines -> identifier EQUAL identifier operator number','lines',5,'p_addnum','mygrammar.py',71),
  ('lines -> identifier EQUAL number operator identifier','lines',5,'p_addnum1','mygrammar.py',75),
  ('lines -> identifier EQUAL number operator number','lines',5,'p_addnum2','mygrammar.py',79),
  ('lines -> identifier EQUAL identifier operator identifier','lines',5,'p_addnum3','mygrammar.py',83),
]
