
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '38500BEF920AB660E5D0D089007F91C8'
    
_lr_action_items = {'RPAREN':([2,4,5,6,7,9,10,],[-2,-4,-3,-6,9,-1,-5,]),'NUMBER':([0,4,8,],[2,2,2,]),'COMMA':([2,6,9,],[-2,8,-1,]),'LPAREN':([3,],[4,]),'IDENTIFIER':([0,4,8,],[3,3,3,]),'$end':([1,2,9,],[0,-2,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'args':([4,8,],[5,10,]),'exp':([0,4,8,],[1,6,6,]),'optargs':([4,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> IDENTIFIER LPAREN optargs RPAREN','exp',4,'p_exp_call','jsfuncall.py',59),
  ('exp -> NUMBER','exp',1,'p_exp_number','jsfuncall.py',63),
  ('optargs -> args','optargs',1,'p_optargs','jsfuncall.py',67),
  ('optargs -> <empty>','optargs',0,'p_optargsempty','jsfuncall.py',71),
  ('args -> exp COMMA args','args',3,'p_args','jsfuncall.py',75),
  ('args -> exp','args',1,'p_args_last','jsfuncall.py',79),
]
